#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MMUSIS1
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="usersdb")]
	public partial class DataClasses1DataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertStudAttendance(StudAttendance instance);
    partial void UpdateStudAttendance(StudAttendance instance);
    partial void DeleteStudAttendance(StudAttendance instance);
    #endregion
		
		public DataClasses1DataContext() : 
				base(global::MMUSIS1.Properties.Settings.Default.usersdbConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<StudAttendance> StudAttendances
		{
			get
			{
				return this.GetTable<StudAttendance>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.StudAttendance")]
	public partial class StudAttendance : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _StudID;
		
		private string _Name;
		
		private string _Geolocation;
		
		private string _StudDate;
		
		private string _Unit;
		
		private string _Course;
		
		private string _Faculty;
		
		private string _AdmNo;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnStudIDChanging(int value);
    partial void OnStudIDChanged();
    partial void OnNameChanging(string value);
    partial void OnNameChanged();
    partial void OnGeolocationChanging(string value);
    partial void OnGeolocationChanged();
    partial void OnStudDateChanging(string value);
    partial void OnStudDateChanged();
    partial void OnUnitChanging(string value);
    partial void OnUnitChanged();
    partial void OnCourseChanging(string value);
    partial void OnCourseChanged();
    partial void OnFacultyChanging(string value);
    partial void OnFacultyChanged();
    partial void OnAdmNoChanging(string value);
    partial void OnAdmNoChanged();
    #endregion
		
		public StudAttendance()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StudID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int StudID
		{
			get
			{
				return this._StudID;
			}
			set
			{
				if ((this._StudID != value))
				{
					this.OnStudIDChanging(value);
					this.SendPropertyChanging();
					this._StudID = value;
					this.SendPropertyChanged("StudID");
					this.OnStudIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="VarChar(80)")]
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				if ((this._Name != value))
				{
					this.OnNameChanging(value);
					this.SendPropertyChanging();
					this._Name = value;
					this.SendPropertyChanged("Name");
					this.OnNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Geolocation", DbType="VarChar(250)")]
		public string Geolocation
		{
			get
			{
				return this._Geolocation;
			}
			set
			{
				if ((this._Geolocation != value))
				{
					this.OnGeolocationChanging(value);
					this.SendPropertyChanging();
					this._Geolocation = value;
					this.SendPropertyChanged("Geolocation");
					this.OnGeolocationChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StudDate", DbType="VarChar(100)")]
		public string StudDate
		{
			get
			{
				return this._StudDate;
			}
			set
			{
				if ((this._StudDate != value))
				{
					this.OnStudDateChanging(value);
					this.SendPropertyChanging();
					this._StudDate = value;
					this.SendPropertyChanged("StudDate");
					this.OnStudDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Unit", DbType="VarChar(150)")]
		public string Unit
		{
			get
			{
				return this._Unit;
			}
			set
			{
				if ((this._Unit != value))
				{
					this.OnUnitChanging(value);
					this.SendPropertyChanging();
					this._Unit = value;
					this.SendPropertyChanged("Unit");
					this.OnUnitChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Course", DbType="VarChar(100)")]
		public string Course
		{
			get
			{
				return this._Course;
			}
			set
			{
				if ((this._Course != value))
				{
					this.OnCourseChanging(value);
					this.SendPropertyChanging();
					this._Course = value;
					this.SendPropertyChanged("Course");
					this.OnCourseChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Faculty", DbType="VarChar(100)")]
		public string Faculty
		{
			get
			{
				return this._Faculty;
			}
			set
			{
				if ((this._Faculty != value))
				{
					this.OnFacultyChanging(value);
					this.SendPropertyChanging();
					this._Faculty = value;
					this.SendPropertyChanged("Faculty");
					this.OnFacultyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AdmNo", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string AdmNo
		{
			get
			{
				return this._AdmNo;
			}
			set
			{
				if ((this._AdmNo != value))
				{
					this.OnAdmNoChanging(value);
					this.SendPropertyChanging();
					this._AdmNo = value;
					this.SendPropertyChanged("AdmNo");
					this.OnAdmNoChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
